#!/bin/bash
# Generate stress test .tc files for TC-Compiler
#
# Run: bash tests/stress/gen_stress_tests.sh
# Regenerates: deep_recursion.tc, let_chain.tc, io_stress.tc,
#              many_vars_stress.tc, type_combinatorial.tc
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"

echo "=== Generating stress tests ==="

# ============================================================
# 1. deep_recursion.tc
#    200-level sequential operation chain
#    TC 的 rhs 语法不支持函数调用嵌套（操作数只能是变量/字面量），
#    因此 "深层递归" 测试使用长链顺序运算来测试：
#    - Parser 多语句吞吐
#    - Executor 顺序运算循环
#    - AST 节点内存管理
#    Pattern: v0=0; v1=add(int32,wrap,v0,1); v2=add(int32,wrap,v1,1); ...
#    Result: v199 = 199
# ============================================================
echo "  -> deep_recursion.tc"
cat > "$ROOT/deep_recursion.tc" << TC_HEADER
; Stress test: 200-level sequential operation chain
; TC 的操作数只能是变量/字面量（不支持函数调用嵌套），
; 因此用长链顺序运算模拟深层递归场景：
;   v0 = 0; v1 = add(int32, wrap, v0, 1); v2 = add(int32, wrap, v1, 1); ...
; Tests: parser multi-stmt throughput, executor loop scalability
; Expected: v199 = 199
; Warning: This file is machine-generated by gen_stress_tests.sh
TC_HEADER

echo "var v0: int32 = 0" >> "$ROOT/deep_recursion.tc"
for i in $(seq 1 199); do
    prev=$((i - 1))
    echo "var v${i}: int32 = add(int32, wrap, v${prev}, 1)" >> "$ROOT/deep_recursion.tc"
done
echo "writeln(int32, v199)" >> "$ROOT/deep_recursion.tc"

echo "    expected: 199"

# ============================================================
# 2. let_chain.tc
#    50-level let dependency chain
#    let a_n: int64 = add(int64, a_{n-1}, a_{n-1})
#    Result: a_0 = 1, a_n = 2^n; a_50 = 2^50 = 1125899906842624
# ============================================================
echo "  -> let_chain.tc"
cat > "$ROOT/let_chain.tc" << 'TC_HEADER2'
; Stress test: 50-level let dependency chain
; Tests analyzer const resolution depth for chained let constants
; a_0 = 1, a_n = add(int64, a_{n-1}, a_{n-1}) = 2^n
; Expected output: a_50 = 2^50 = 1125899906842624
; Warning: This file is machine-generated by gen_stress_tests.sh
TC_HEADER2

echo "let a0: int64 = 1" >> "$ROOT/let_chain.tc"
for i in $(seq 1 50); do
    prev=$((i - 1))
    echo "let a${i}: int64 = add(int64, a${prev}, a${prev})" >> "$ROOT/let_chain.tc"
done
echo "writeln(int64, a50)" >> "$ROOT/let_chain.tc"

# Verify: 2^50 = 1125899906842624
echo "    expected: 1125899906842624"

# ============================================================
# 3. io_stress.tc
#    128 writeln calls outputting numbers 0 through 127
#    Tests I/O subsystem with high volume of output operations
# ============================================================
echo "  -> io_stress.tc"
cat > "$ROOT/io_stress.tc" << 'TC_HEADER3'
; Stress test: 128 writeln calls outputting 0..127
; Tests I/O subsystem throughput with high volume output
; Expected output: "0\n1\n2\n...\n127\n"
; Warning: This file is machine-generated by gen_stress_tests.sh
TC_HEADER3

for i in $(seq 0 127); do
    echo "writeln(int32, $i)" >> "$ROOT/io_stress.tc"
done

echo "    expected: 0..127 each on a new line"

# ============================================================
# 4. many_vars_stress.tc
#    300+ variable/let definitions across all types
#    Tests symbol table capacity and lookup performance
# ============================================================
echo "  -> many_vars_stress.tc"
cat > "$ROOT/many_vars_stress.tc" << 'TC_HEADER4'
; Stress test: 300+ variable/let definitions across all integer types
; Tests symbol table capacity and lookup performance
; a-chain (int8):   a_n = a_{n-1} + (n+1)    → a49 = 1275
; b-chain (int32):  b_n = b_{n-1} + (n+1)    → b49 = 1275
; c-chain (int64):  c_n = c_{n-1} + (n+1)*10 → c49 = 12750
; d-chain (uint8):  d_n = d_{n-1} + (n+1)    → d49 = 1275
; e-chain (uint32): e_n = e_{n-1} + (n+1)    → e49 = 1275
; f-chain (let int64): f_n = 2^n             → f49 = 562949953421312
; g-chain (let int32): g_n = 3^n             → g49 = 3^49 (wraps in int32, tests compile-time eval)
; Warning: This file is machine-generated by gen_stress_tests.sh
TC_HEADER4

# a-chain: int8, wrap mode to avoid strict overflow
# a_n = sum(1..n+1) = (n+1)(n+2)/2
echo "var a0: int8 = 1" >> "$ROOT/many_vars_stress.tc"
for i in $(seq 1 49); do
    inc=$((i + 1))
    echo "var a${i}: int8 = add(int8, wrap, a$((i-1)), ${inc})" >> "$ROOT/many_vars_stress.tc"
done

# b-chain: int32
echo "var b0: int32 = 1" >> "$ROOT/many_vars_stress.tc"
for i in $(seq 1 49); do
    inc=$((i + 1))
    echo "var b${i}: int32 = add(int32, b$((i-1)), ${inc})" >> "$ROOT/many_vars_stress.tc"
done

# c-chain: int64
echo "var c0: int64 = 10" >> "$ROOT/many_vars_stress.tc"
for i in $(seq 1 49); do
    inc=$(( (i + 1) * 10 ))
    echo "var c${i}: int64 = add(int64, c$((i-1)), ${inc})" >> "$ROOT/many_vars_stress.tc"
done

# d-chain: uint8
echo "var d0: uint8 = 1" >> "$ROOT/many_vars_stress.tc"
for i in $(seq 1 49); do
    inc=$((i + 1))
    echo "var d${i}: uint8 = add(uint8, d$((i-1)), ${inc})" >> "$ROOT/many_vars_stress.tc"
done

# e-chain: uint32
echo "var e0: uint32 = 1" >> "$ROOT/many_vars_stress.tc"
for i in $(seq 1 49); do
    inc=$((i + 1))
    echo "var e${i}: uint32 = add(uint32, e$((i-1)), ${inc})" >> "$ROOT/many_vars_stress.tc"
done

# f-chain: let int64, f_n = 2^n
echo "let f0: int64 = 1" >> "$ROOT/many_vars_stress.tc"
for i in $(seq 1 49); do
    echo "let f${i}: int64 = add(int64, f$((i-1)), f$((i-1)))" >> "$ROOT/many_vars_stress.tc"
done

# Output: verify known values
echo "writeln(int32, b49)"  >> "$ROOT/many_vars_stress.tc"    # 1275
echo "writeln(int64, c49)"  >> "$ROOT/many_vars_stress.tc"    # 12750
echo "writeln(int64, f49)"  >> "$ROOT/many_vars_stress.tc"    # 562949953421312

# b49 = sum(2..50) = (50*51/2 - 1) = 1275 - 1 = 1274? Let me recalculate.
# b0 = 1
# b1 = b0 + 2 = 3
# b2 = b1 + 3 = 6
# b_n = sum(1..n+1) = (n+1)(n+2)/2
# b49 = 50*51/2 = 1275
echo "    expected b49: 1275"
# c49 = sum of (i+1)*10 for i=0..49, plus c0=10 prefix
# c0 = 10
# c1 = 10 + 20 = 30
# c2 = 30 + 30 = 60
# c_n = 10 * sum(1..n+1) = 10 * (n+1)(n+2)/2
# c49 = 10 * 1275 = 12750
echo "    expected c49: 12750"
# f49 = 2^49 = 562949953421312
echo "    expected f49: 562949953421312"

# ============================================================
# 5. type_combinatorial.tc
#    All types across all operator categories
#    Covers: ARITH, UNARY, COMPARE, LOGIC_BIN, LOGIC_UN, CAST, I/O
#    Tests all 8 integer types + bool across every TcRhsKind
# ============================================================
echo "  -> type_combinatorial.tc"
cat > "$ROOT/type_combinatorial.tc" << 'TC_HEADER5'
; Stress test: All types across all operators
; Covers every TcRhsKind for every type:
;   ARITH (add/sub/mul), DIVISION (div/mod), UNARY (abs/neg),
;   COMPARE (eq/lt), LOGIC (and/or/not), CAST, I/O
; Tests: int8, int16, int32, int64, uint8, uint16, uint32, uint64, bool
; Warning: This file is machine-generated by gen_stress_tests.sh
TC_HEADER5

# Helper function: add type operations section
add_type_section() {
    local type=$1
    local unsigned=$2
    local val_a=$3
    local val_b=$4
    local val_c=$5       # for sub (val_a - val_b)
    local val_d=$6       # for mul (val_a * val_b)
    local val_e=$7       # for div (val_a / val_b)
    local val_f=$8       # for mod (val_a % val_b)

    echo "; === ${type} operations ===" >> "$ROOT/type_combinatorial.tc"

    # ARITH: add, sub, mul
    echo "var t_${type}_add: ${type} = add(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"
    echo "var t_${type}_sub: ${type} = sub(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"
    echo "var t_${type}_mul: ${type} = mul(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"

    # DIVISION: div, mod (only if val_b != 0)
    echo "var t_${type}_div: ${type} = div(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"
    echo "var t_${type}_mod: ${type} = mod(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"

    # UNARY: abs, neg
    local neg_val
    if [ "$unsigned" = "1" ]; then
        neg_val=$val_a  # unsigned: use val_a directly (neg on unsigned is allowed but use positive)
    else
        neg_val=$val_a
    fi
    echo "var t_${type}_neg: ${type} = neg(${type}, ${neg_val})" >> "$ROOT/type_combinatorial.tc"
    echo "var t_${type}_abs: ${type} = abs(${type}, ${neg_val})" >> "$ROOT/type_combinatorial.tc"

    # COMPARE: eq, lt (result is bool)
    echo "var t_${type}_eq: bool = eq(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"
    echo "var t_${type}_lt: bool = lt(${type}, ${val_a}, ${val_b})" >> "$ROOT/type_combinatorial.tc"

    # I/O: write values
    echo "writeln(${type}, t_${type}_add)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(${type}, t_${type}_sub)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(${type}, t_${type}_mul)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(${type}, t_${type}_div)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(${type}, t_${type}_mod)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(${type}, t_${type}_neg)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(${type}, t_${type}_abs)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(bool, t_${type}_eq)" >> "$ROOT/type_combinatorial.tc"
    echo "writeln(bool, t_${type}_lt)" >> "$ROOT/type_combinatorial.tc"
}

# int8: signed 8-bit
add_type_section "int8" "0" "10" "3" "7" "30" "3" "1"

# int16: signed 16-bit
add_type_section "int16" "0" "100" "30" "70" "3000" "3" "10"

# int32: signed 32-bit
add_type_section "int32" "0" "1000" "300" "700" "300000" "3" "100"

# int64: signed 64-bit
add_type_section "int64" "0" "10000" "3000" "7000" "30000000" "3" "1000"

# uint8: unsigned 8-bit
add_type_section "uint8" "1" "10" "3" "7" "30" "3" "1"

# uint16: unsigned 16-bit
add_type_section "uint16" "1" "100" "30" "70" "3000" "3" "10"

# uint32: unsigned 32-bit
add_type_section "uint32" "1" "1000" "300" "700" "300000" "3" "100"

# uint64: unsigned 64-bit
add_type_section "uint64" "1" "10000" "3000" "7000" "30000000" "3" "1000"

# bool section: LOGIC_BIN, LOGIC_UN, CAST
echo "; === bool operations ===" >> "$ROOT/type_combinatorial.tc"

echo "var t_bool_and: bool = and(bool, true, false)" >> "$ROOT/type_combinatorial.tc"
echo "var t_bool_or: bool = or(bool, true, false)" >> "$ROOT/type_combinatorial.tc"
echo "var t_bool_not: bool = not(bool, true)" >> "$ROOT/type_combinatorial.tc"
echo "var t_bool_not2: bool = not(bool, false)" >> "$ROOT/type_combinatorial.tc"
echo "writeln(bool, t_bool_and)" >> "$ROOT/type_combinatorial.tc"     # false
echo "writeln(bool, t_bool_or)" >> "$ROOT/type_combinatorial.tc"      # true
echo "writeln(bool, t_bool_not)" >> "$ROOT/type_combinatorial.tc"     # false
echo "writeln(bool, t_bool_not2)" >> "$ROOT/type_combinatorial.tc"    # true

# Cast operations: each type to next wider type
echo "; === cast operations across types ===" >> "$ROOT/type_combinatorial.tc"
echo "var cast_src8: int8 = -100" >> "$ROOT/type_combinatorial.tc"
echo "var cast_to16: int16 = cast(int16, cast_src8)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_to32: int32 = cast(int32, cast_to16)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_to64: int64 = cast(int64, cast_to32)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_src_u: int32 = 200" >> "$ROOT/type_combinatorial.tc"
echo "var cast_u8: uint8 = cast(uint8, cast_src_u)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_to_u16: uint16 = cast(uint16, cast_u8)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_to_u32: uint32 = cast(uint32, cast_to_u16)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_to_u64: uint64 = cast(uint64, cast_to_u32)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_bool_from_i8: bool = cast(bool, cast_src8)" >> "$ROOT/type_combinatorial.tc"
echo "var cast_bool_src: bool = true" >> "$ROOT/type_combinatorial.tc"
echo "var cast_i8_from_bool: int8 = cast(int8, cast_bool_src)" >> "$ROOT/type_combinatorial.tc"

echo "writeln(int16, cast_to16)" >> "$ROOT/type_combinatorial.tc"     # -100
echo "writeln(int32, cast_to32)" >> "$ROOT/type_combinatorial.tc"     # -100
echo "writeln(int64, cast_to64)" >> "$ROOT/type_combinatorial.tc"     # -100
echo "writeln(uint16, cast_to_u16)" >> "$ROOT/type_combinatorial.tc"  # 200
echo "writeln(uint32, cast_to_u32)" >> "$ROOT/type_combinatorial.tc"  # 200
echo "writeln(uint64, cast_to_u64)" >> "$ROOT/type_combinatorial.tc"  # 200
echo "writeln(bool, cast_bool_from_i8)" >> "$ROOT/type_combinatorial.tc"  # true
echo "writeln(int8, cast_i8_from_bool)" >> "$ROOT/type_combinatorial.tc"  # 1

# Format specifiers: test %d, %u, %x, %o, %b on representative types
echo "; === format specifier stress ===" >> "$ROOT/type_combinatorial.tc"
echo "var fmt_src: int32 = 255" >> "$ROOT/type_combinatorial.tc"
echo "write(int32, fmt_src)" >> "$ROOT/type_combinatorial.tc"                          # 255 (no specifier = %d)
echo "write(int32, %d, fmt_src)" >> "$ROOT/type_combinatorial.tc"                      # 255
echo "write(int32, %x, fmt_src)" >> "$ROOT/type_combinatorial.tc"                      # ff
echo "write(int32, %X, fmt_src)" >> "$ROOT/type_combinatorial.tc"                      # FF
echo "write(int32, %o, fmt_src)" >> "$ROOT/type_combinatorial.tc"                      # 377
echo "write(int32, %b, fmt_src)" >> "$ROOT/type_combinatorial.tc"                      # 11111111
echo "var fmt_src_u: uint32 = 255" >> "$ROOT/type_combinatorial.tc"
echo "write(uint32, %u, fmt_src_u)" >> "$ROOT/type_combinatorial.tc"                   # 255
echo "write(uint32, %x, fmt_src_u)" >> "$ROOT/type_combinatorial.tc"                   # ff
echo "writeln(int32, 0)" >> "$ROOT/type_combinatorial.tc"                               # newline + terminator

echo "    expected: many lines of output"
echo ""
echo "=== Generation complete ==="
echo "Generated files:"
ls -la "$ROOT/deep_recursion.tc" "$ROOT/let_chain.tc" "$ROOT/io_stress.tc" \
      "$ROOT/many_vars_stress.tc" "$ROOT/type_combinatorial.tc"
