#!/bin/sh
set -e

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VM_BIN="$ROOT/build/vm/bin/tc-vm"
STRESS="$ROOT/tests/stress/massive_vars.tc"
BASELINE="$ROOT/tests/stress/bench_baseline.tc"
LIMITS="$ROOT/tests/stress/bench_limits.txt"

CHECK_MODE=0
UPDATE_LIMITS=0
MULTIPLIER=5
ANY_FAIL=0
LIMITS_TMP=""

usage() {
    echo "用法: $0 [--check] [--update-limits] [--multiplier N]" >&2
    echo "  --check          对照 bench_limits.txt 检测性能退化（CI 用）" >&2
    echo "  --update-limits  按当前实测 × multiplier 刷新上限（默认 ×5）" >&2
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
    --check)
        CHECK_MODE=1
        shift
        ;;
    --update-limits)
        UPDATE_LIMITS=1
        shift
        ;;
    --multiplier)
        if [ $# -lt 2 ]; then
            usage
        fi
        MULTIPLIER="$2"
        shift 2
        ;;
    --help|-h)
        usage
        ;;
    *)
        echo "error: unknown option: $1" >&2
        usage
        ;;
    esac
done

if [ ! -x "$VM_BIN" ]; then
    echo "error: tc-vm not found at $VM_BIN (run: make vm)" >&2
    exit 1
fi

lookup_limit() {
    label="$1"
    mode="$2"
    phase="$3"
    if [ ! -f "$LIMITS" ]; then
        return 1
    fi
    awk -v label="$label" -v mode="$mode" -v phase="$phase" '
        /^#/ || NF == 0 { next }
        $1 == label && $2 == mode && $3 == phase { print $4; found = 1; exit }
        END { if (!found) exit 1 }
    ' "$LIMITS"
}

check_timing() {
    label="$1"
    mode="$2"
    phase="$3"
    seconds="$4"

    if [ "$CHECK_MODE" -eq 0 ]; then
        return 0
    fi

    limit=$(lookup_limit "$label" "$mode" "$phase") || {
        echo "error: no limit for $label $mode $phase in $LIMITS" >&2
        ANY_FAIL=1
        return 1
    }
    if awk -v s="$seconds" -v lim="$limit" 'BEGIN { exit (s + 0 > lim + 0) ? 1 : 0 }'; then
        return 0
    fi
    echo "error: $label/$mode/$phase ${seconds}s exceeds limit ${limit}s" >&2
    ANY_FAIL=1
    return 1
}

record_limit_line() {
    label="$1"
    mode="$2"
    phase="$3"
    seconds="$4"
    if [ "$UPDATE_LIMITS" -eq 0 ] || [ -z "$LIMITS_TMP" ]; then
        return 0
    fi
    new_limit=$(awk -v s="$seconds" -v m="$MULTIPLIER" 'BEGIN { printf "%.6f", s * m }')
    echo "$label $mode $phase $new_limit" >> "$LIMITS_TMP"
}

bench_one() {
    label="$1"
    file="$2"
    mode="$3"
    check_flag=""
    if [ "$mode" = "check" ]; then
        check_flag="--check"
    fi

    echo "=== $label ($mode) ==="
    OUT=$(mktemp)
    TC_BENCH=1 "$VM_BIN" $check_flag "$file" </dev/null 2>&1 | grep '^bench ' > "$OUT" || true
    while IFS= read -r line; do
        phase=$(echo "$line" | sed -n 's/^bench \([^:]*\):.*/\1/p')
        seconds=$(echo "$line" | sed -n 's/^bench [^:]*: \([0-9.]*\) s/\1/p')
        echo "$line"
        check_timing "$label" "$mode" "$phase" "$seconds" || true
        record_limit_line "$label" "$mode" "$phase" "$seconds"
    done < "$OUT"
    rm -f "$OUT"
    echo ""
}

run_suite() {
    label="$1"
    file="$2"
    bench_one "$label" "$file" "check"
    bench_one "$label" "$file" "run"
}

if [ "$UPDATE_LIMITS" -eq 1 ]; then
    LIMITS_TMP=$(mktemp)
    {
        echo "# Auto-generated by scripts/vm/bench.sh --update-limits (multiplier=${MULTIPLIER})"
        echo "# Format: label mode phase max_seconds"
    } > "$LIMITS_TMP"
    run_suite "massive_vars" "$STRESS"
    if [ -f "$BASELINE" ]; then
        run_suite "bench_baseline" "$BASELINE"
    fi
    mv "$LIMITS_TMP" "$LIMITS"
    echo "updated $LIMITS (multiplier=${MULTIPLIER})"
    exit 0
fi

echo "TC-VM performance benchmark"
echo "Host: $(uname -srm 2>/dev/null || echo unknown)"
if [ "$CHECK_MODE" -eq 1 ]; then
    echo "Mode: regression check (limits: $LIMITS)"
fi
echo ""

run_suite "massive_vars" "$STRESS"

if [ -f "$BASELINE" ]; then
    run_suite "bench_baseline" "$BASELINE"
else
    echo "=== bench_baseline (skipped, file missing — run gen_bench_baseline.sh) ==="
    echo ""
fi

if [ "$CHECK_MODE" -eq 1 ]; then
    if [ "$ANY_FAIL" -ne 0 ]; then
        echo "bench regression check FAILED" >&2
        exit 1
    fi
    echo "bench regression check passed"
else
    echo "Tip: --check 对照 bench_limits.txt；--update-limits 刷新上限"
fi
