/* Auto-generated by tc-aot from tests/valid/example.tc. Do not edit. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "tc_aot_rt.h"

static uint64_t slots[4];

int main(void) {
    TcDiagnostic diag;
    tc_aot_diag_init(&diag);
    tc_aot_init_slots(slots, 4);

    slots[0] = tc_aot_lit(TC_INT32, 10ULL, 0, 0);
    slots[1] = tc_aot_lit(TC_INT32, 20ULL, 0, 0);
    if (tc_aot_arith(TC_ADD, TC_INT32, TC_ARITH_STRICT, &slots[2], slots[0], slots[1], &diag, 3) != 0)
        tc_aot_abort(&diag, 3);
    if (tc_aot_cast(TC_INT8, TC_TRUNC_TRUNCATE, slots[2], TC_INT32, &slots[3], &diag, 4) != 0)
        tc_aot_abort(&diag, 4);

    return 0;
}
