/* Auto-generated by tc-aot. Do not edit. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "tc_aot_rt.h"

static uint64_t slots[4];

static TcDiagnostic *tc_aot_cur_diag;

static void tc_init_static_vars(TcDiagnostic *diag) {
    tc_aot_cur_diag = diag;
}

int main(void) {
    TcDiagnostic diag;
    tc_aot_diag_init(&diag);
    tc_aot_cur_diag = &diag;
    if (tc_diagnostic_set_source(&diag, "tests/valid/example.tc", NULL) != 0) {
        tc_aot_abort(&diag, 0);
    }
    tc_aot_init_slots(slots, 4);
    tc_init_static_vars(&diag);
    if (diag.domain != TC_DIAG_NONE) tc_aot_abort(&diag, 0);

    slots[0] = tc_aot_lit(TC_INT32, 10ULL, 0, 0);
    slots[1] = tc_aot_lit(TC_INT32, 20ULL, 0, 0);
    if (tc_aot_arith(TC_ADD, TC_INT32, TC_ARITH_STRICT, &slots[2], slots[0], slots[1], tc_aot_cur_diag, 4) != 0)
        tc_aot_abort(tc_aot_cur_diag, 4);
    if (tc_aot_cast(TC_INT8, TC_TRUNC_TRUNCATE, slots[2], TC_INT32, &slots[3], tc_aot_cur_diag, 5) != 0)
        tc_aot_abort(tc_aot_cur_diag, 5);

    tc_aot_memblock_heap_free_all();
    tc_aot_struct_heap_free_all();
    return 0;
}
